{{- range .Values.secrets }}
{{- if .enabled }}
{{- $secret := . }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "helm.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ .refreshInterval | default (index $.Values.secretsDefaults "refreshInterval") | default "1h" }}
  secretStoreRef:
    {{- if .secretStoreRef }}
    name: {{ .secretStoreRef.name | default (index $.Values.secretsDefaults.secretStoreRef "name") | default "aws-secrets" }}
    kind: {{ .secretStoreRef.kind | default (index $.Values.secretsDefaults.secretStoreRef "kind") | default "ClusterSecretStore" }}
    {{- else }}
    name: {{ index $.Values.secretsDefaults.secretStoreRef "name" | default "aws-secrets" }}
    kind: {{ index $.Values.secretsDefaults.secretStoreRef "kind" | default "ClusterSecretStore" }}
    {{- end }}
  target:
    name: {{ .name }}
    creationPolicy: Owner
  data:
  {{- range $envKey, $remoteKey := .env }}
    - secretKey: {{ $envKey }}
      remoteRef:
        key: {{ $secret.aws.secretName }}
        property: {{ $remoteKey }}
  {{- end }}
---
{{- end }}
{{- end }}
