{{- range .Values.secrets }}
{{- if .enabled }}
{{- $secret := . }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "helm.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ .refreshInterval | default $.Values.secretsDefaults.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .secretStoreRef.name | default $.Values.secretsDefaults.secretStoreRef.name | default "aws-secrets" }}
    kind: {{ .secretStoreRef.kind | default $.Values.secretsDefaults.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: {{ .name }}
    creationPolicy: Owner
  data:
  {{- range $envKey, $remoteKey := .env }}
    - secretKey: {{ $envKey }}
      remoteRef:
        key: {{ $secret.aws.secretName }}
        property: {{ $remoteKey }}
  {{- end }}
---
{{- end }}
{{- end }}
