apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/devozz32/gitops.git  # Update with your Git repository URL
    targetRevision: main # Or specify a branch/tag (e.g., main, master, v1.0.0)
    path: apps  # Path to directory containing application definitions
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

